"""Add demo usage tracking

Revision ID: e1ab09310b66
Revises: 2dec08938fad
Create Date: 2025-08-01 17:08:24.175573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ab09310b66'
down_revision: Union[str, None] = '2dec08938fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_usage', sa.Column('message_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_usage', 'message_count')
    # ### end Alembic commands ###
